/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.*;
import java.awt.Color;
import java.awt.Container;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Simon
 */
public class NapakalakiView extends javax.swing.JFrame {
    public Napakalaki napakalakiModel;
    private boolean juego_terminado=false;
    
    public void setNapakalaki(Napakalaki n){
        napakalakiModel=n;
        
        this.monsterView1.setVisible(false);
        this.combatresult.setVisible(false);
        this.combatresult2.setVisible(false);
        this.button_meet_monster.setEnabled(true);
        this.button_combat.setEnabled(false);
        this.button_next_turn.setEnabled(false);
        
        this.monsterView1.setMonster(napakalakiModel.getCurrentMonster());
        this.playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
        this.playerView1.setNapakalakiModel(napakalakiModel);
        
        repaint();
        revalidate();
    }
    
    /**
     * Creates new form NapakalakiView
     */
    public NapakalakiView() {
        initComponents();
        this.setBackground(Color.CYAN);
        this.setLocationRelativeTo(null);
        String path = "images/title.png";   
        URL url = this.getClass().getResource(path); 
        ImageIcon icon = new ImageIcon(url);
  
        this.image.setIcon(icon);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        monsterView1 = new GUI.MonsterView();
        playerView1 = new GUI.PlayerView();
        button_combat = new javax.swing.JButton();
        button_next_turn = new javax.swing.JButton();
        button_meet_monster = new javax.swing.JButton();
        text_combatresult = new javax.swing.JLabel();
        combatresult = new javax.swing.JLabel();
        combatresult2 = new javax.swing.JLabel();
        image = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 204));

        button_combat.setText("Combat");
        button_combat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_combatActionPerformed(evt);
            }
        });

        button_next_turn.setText("Next Turn");
        button_next_turn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_next_turnActionPerformed(evt);
            }
        });

        button_meet_monster.setText("Meet the Monster");
        button_meet_monster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_meet_monsterActionPerformed(evt);
            }
        });

        text_combatresult.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        text_combatresult.setText("COMBAT RESULT:");

        combatresult.setText("result");

        combatresult2.setText("result2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(text_combatresult)
                            .addComponent(combatresult)
                            .addComponent(combatresult2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(button_meet_monster)
                                    .addComponent(button_next_turn)
                                    .addComponent(button_combat))))
                        .addGap(291, 291, 291)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(monsterView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(button_meet_monster)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_combat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button_next_turn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(text_combatresult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combatresult)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(combatresult2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(playerView1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_meet_monsterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_meet_monsterActionPerformed
        // TODO add your handling code here:
        this.monsterView1.setVisible(true);
        this.button_combat.setEnabled(true);
        this.button_meet_monster.setEnabled(false);
        this.playerView1.DiscoveredMonster();
    }//GEN-LAST:event_button_meet_monsterActionPerformed

    private void button_combatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_combatActionPerformed
        // TODO add your handling code here:
        CombatResult result = napakalakiModel.developCombat();
        this.combatresult2.setText(" ");
        switch (result) {
            case WINGAME: 
                this.combatresult.setText("YOU'VE WINNED THE GAME!");
                juego_terminado=true;
                break;
            case WIN :
                this.combatresult.setText("Defeated enemy, you win.");
                break;
            case LOSE :
                this.combatresult.setText("You've lost the combat.");
                break;
            case LOSEANDCONVERT :
                this.combatresult.setText("You've lost the combat and you've become a cultist.");
                this.combatresult2.setText("Anyway, you've have to accomplish the bad consequence.");
                break;
        }
        this.combatresult.setVisible(true);
        this.combatresult2.setVisible(true);
        this.playerView1.get_button_make_visible().setEnabled(true);
        this.button_next_turn.setEnabled(true);
        this.button_combat.setEnabled(false);
        this.playerView1.UndiscoveredMonster();
        this.playerView1.setPlayer(napakalakiModel.getCurrentPlayer());
    }//GEN-LAST:event_button_combatActionPerformed
    
    private void button_next_turnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_next_turnActionPerformed
        // TODO add your handling code here:
        if(juego_terminado){
            WinnerView winner=new WinnerView(this,true,napakalakiModel.getCurrentPlayer().getName());
            winner.setVisible(true);
            System.exit(0);
        }
        if(napakalakiModel.nextTurn()){
            this.setNapakalaki(napakalakiModel);
        }else{
            ErrorNextTurn error=new ErrorNextTurn(this,true);
            error.setVisible(true);
        }
    }//GEN-LAST:event_button_next_turnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button_combat;
    private javax.swing.JButton button_meet_monster;
    private javax.swing.JButton button_next_turn;
    private javax.swing.JLabel combatresult;
    private javax.swing.JLabel combatresult2;
    private javax.swing.JLabel image;
    private GUI.MonsterView monsterView1;
    private GUI.PlayerView playerView1;
    private javax.swing.JLabel text_combatresult;
    // End of variables declaration//GEN-END:variables
}