/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import NapakalakiGame.Treasure;
import java.awt.Color;

/**
 *
 * @author Simon
 */
public class TreasureView extends javax.swing.JPanel {
    private Treasure treasureModel;
    private boolean selected=false;
    /**
     * Creates new form TreasureView
     */
    public TreasureView() {
        initComponents();
        setBackground(Color.LIGHT_GRAY);
    }

    public void setTreasure(Treasure t){
        treasureModel=t;
        
        this.name.setText(treasureModel.getName());
        this.bonus.setText(Integer.toString(treasureModel.getBonus()));
        this.type.setText(treasureModel.getType().toString());
        
        repaint();
        revalidate();
    }
    
    public boolean isSelected(){
        return selected;
    }
    
    public Treasure getTreasure(){
        return treasureModel;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AKSJAKSDJASKDJSAD = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        bonus = new javax.swing.JLabel();
        type = new javax.swing.JLabel();
        bonus_text = new javax.swing.JLabel();
        type_text = new javax.swing.JLabel();

        AKSJAKSDJASKDJSAD.setText("eeee que estoy aquiii");

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });

        name.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("jLabel1");
        name.setToolTipText("");
        name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bonus.setText("jLabel1");
        bonus.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        type.setText("jLabel 2");
        type.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        bonus_text.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bonus_text.setText("Bonus:");
        bonus_text.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        type_text.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        type_text.setText("Type:");
        type_text.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bonus_text)
                            .addComponent(bonus))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(type_text))
                            .addComponent(type, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 18, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(name, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bonus_text)
                    .addComponent(type_text))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bonus)
                    .addComponent(type))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        
        if (selected){
            selected = false;
            setBackground(Color.LIGHT_GRAY);
            repaint();
        }else{
            selected = true;
            setBackground(Color.GRAY);
            repaint();
        }
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AKSJAKSDJASKDJSAD;
    private javax.swing.JLabel bonus;
    private javax.swing.JLabel bonus_text;
    private javax.swing.JLabel name;
    private javax.swing.JLabel type;
    private javax.swing.JLabel type_text;
    // End of variables declaration//GEN-END:variables
}
